-- ═══════════════════════════════════════════════════════════════════════════
-- NiImmo: Cron-Registrierung fuer check_zahlungs_anomalien()
--
-- Additiver, taeglicher Korrektur-Check: prueft bereits zugeordnete Zahlungen
-- bei Mietern mit mehreren verbundenen Mietvertraegen (z.B. Wohnung + Garage)
-- auf Betrags-Plausibilitaet und markiert Verdachtsfaelle in
-- public.zahlungs_anomalien. Veraendert NIEMALS bestehende Zuordnungen und
-- fasst supabase/functions/process-payments/index.ts nicht an.
--
-- Hinweis: Die pg_cron-Registrierung (cron.schedule) erfordert erweiterte
-- DB-Rechte (Zugriff auf das cron-Schema) und wurde daher direkt per SQL
-- gegen die verlinkte Datenbank angewandt, nicht ueber die reguläre
-- Migrations-Pipeline. Diese Datei dokumentiert das Setup fuer die
-- Versionsverwaltung (analog zu 20260427000005_pg_cron_native_scheduler.sql).
-- ═══════════════════════════════════════════════════════════════════════════

-- Angewandt:
--   SELECT cron.schedule(
--     'niimmo-check-zahlungs-anomalien',
--     '0 8 * * *',
--     'SELECT check_zahlungs_anomalien()'
--   );
--
-- Ergebnis: jobid 9, taeglich 08:00 UTC, ruft check_zahlungs_anomalien()
-- mit Default-Fenster (60 Tage) auf.
--
-- Zum Entfernen (falls jemals noetig):
--   SELECT cron.unschedule('niimmo-check-zahlungs-anomalien');
-- ═══════════════════════════════════════════════════════════════════════════
